### PR TITLE
New salad

### PR DESCRIPTION
**Pull request by ArturZalutskyi**
cucumber salad recepe

### CODE REVIEW

**Comment by ArturZalutskyi** [comment]
waiting for comments

**Review by LytvynOlena — CHANGES_REQUESTED** [review]
You need to add some chips

**Comment by ArturZalutskyi** [comment]
no chips for salad

**Comment by ArturZalutskyi** [comment]
can you just merje it as is?))

**Comment by LytvynOlena** [comment]
Are you talking to me?can you be more specific please

**Comment by ArturZalutskyi** [comment]
done, I merged it myself))

**Pull request merged**
